/*
IDS projekt: 2. část - SQL skript pro vytvoření objektů schématu databáze
Autoři: 
  - Jana Veronika Moskvová (xmoskv01)
  - Petr Plíhal            (xpliha02)
*/

-- DROP pro všechny tabulky (v opačném pořadí od vytvoření, kvůli cizím klíčům)
DROP TABLE ProvedenyVykon;
DROP TABLE PredepsanyLek;
DROP TABLE Vykon;
DROP TABLE Lek;
DROP TABLE Vysetreni;
DROP TABLE Ockovani;
DROP TABLE Pacient;
DROP TABLE Faktura;
DROP TABLE Navsteva;


create table Navsteva
(
    idNavstevy int GENERATED BY DEFAULT as identity primary key,
    datum date not null,
    cas time not null,
    rodneCislo int REFERENCES Pacient(rodneCislo)
);

create table Faktura
(
    idFaktury int GENERATED BY DEFAULT as identity primary key,
    castka decimal(18,2) check (castka >= 0),
    datumVystaveni date not null,
    popis nvarchar2(255) not null,
    datumSplatnosti date not null,
    idNavstevy int REFERENCES Navsteva(idNavstevy)
);

create table Pacient
(
    rodneCislo number(10) check (mod(rodneCislo,11)=0) primary key,
    jmeno nvarchar2(255) not null,
    prijmeni nvarchar2(255) not null,
    datumNarozeni date not null,
    ulice nvarchar2(255) not null,
    mesto nvarchar2(255) not null,
    psc number(5) not null,
    telefon int not null,
    cisloPojistence int not null
);

create table Ockovani
(
    idNavstevy int primary key references Navsteva(idNavstevy) ON DELETE CASCADE,
    typ nvarchar2(255) not null,
    expirace date not null
);

create table Vysetreni
(
    idNavstevy int primary key references Navsteva(idNavstevy) ON DELETE CASCADE,
    typ nvarchar2(255) not null,
    planovaneVykony nvarchar2(255) not null,
    zazadanaVysetreni nvarchar2(255) not null,
    lekarskaZprava nvarchar2(255) not null
);

create table Lek
(
    idLeku int primary key,
    typ nvarchar2(255) not null,
    davkovani nvarchar2(255) not null,
    nazev nvarchar2(255) not null,
    ucinnaLatka nvarchar2(255) not null
);

create table Vykon
(
    idVykonu int primary key,
    nazevVykonu nvarchar2(255),
    popis nvarchar2(255)
);

create table PredepsanyLek
(
    idNavstevy int REFERENCES Vysetreni(idNavstevy),
    idLeku int REFERENCES Lek(idLeku),
    primary key (idNavstevy, idLeku)
);

create table ProvedenyVykon
(
    idNavstevy int REFERENCES Vysetreni(idNavstevy),
    idVykonu int REFERENCES  Vykon(idVykonu),
    primary key (idNavstevy, idVykonu)
);